/// Flutter icons AppBarIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppBarIcon
///      fonts:
///       - asset: fonts/AppBarIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppBarIcon {
  AppBarIcon._();

  static const _kFontFam = 'AppBarIcon';
  static const _kFontPkg = null;

  static const IconData union = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
