/// Flutter icons BackIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BackIcon
///      fonts:
///       - asset: fonts/BackIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BackIcon {
  BackIcon._();

  static const _kFontFam = 'BackIcon';
  static const _kFontPkg = null;

  static const IconData union = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
