/// Flutter icons BottombarIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottombarIcon
///      fonts:
///       - asset: fonts/BottombarIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottombarIcon {
  BottombarIcon._();

  static const _kFontFam = 'BottombarIcon';
  static const _kFontPkg = null;

  static const IconData mydelivery = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
