/// Flutter icons DriverIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DriverIcon
///      fonts:
///       - asset: fonts/DriverIcon.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class DriverIcon {
  DriverIcon._();

  static const _kFontFam = 'DriverIcon';
  static const _kFontPkg = null;

  static const IconData my_account = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dots = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xf232, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
