/// Flutter icons HomeIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeIcons
///      fonts:
///       - asset: fonts/HomeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeIcons {
  HomeIcons._();

  static const _kFontFam = 'HomeIcons';
  static const _kFontPkg = null;

  static const IconData union = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
