/// Flutter icons MapIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MapIcon
///      fonts:
///       - asset: fonts/MapIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MapIcon {
  MapIcon._();

  static const _kFontFam = 'MapIcon';
  static const _kFontPkg = null;

  static const IconData a_turn_left = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a_turn_right = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a_u_turn_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a_u_turn = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
