/// Flutter icons PermissionSwitchon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PermissionSwitchon
///      fonts:
///       - asset: fonts/PermissionSwitchon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PermissionSwitchon {
  PermissionSwitchon._();

  static const _kFontFam = 'PermissionSwitchon';
  static const _kFontPkg = null;

  static const IconData switcher_3x = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switcher_3x_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
